### ISSUE TITLE
CRITICAL: files of pypi are not the same as in github !!!

### ISSUE THREAD

**Issue by alexgarel** [sobotklp/django-throttle-requests#21]
In the [archive from pypi](https://files.pythonhosted.org/packages/7a/90/233b380a742a0fba262466d8a7cbbb0219d6ad3410f79bd8ff4699e5898a/django-throttle-requests-0.5.8.tar.gz) the file `throttle/zone/__init__.py` at line 65, reads 

```python
bucket_num_next = (bucket_num + 1) % 2
```

where as [in github it is](https://github.com/sobotklp/django-throttle-requests/blob/master/throttle/zones/__init__.py#L65):

```python
bucket_num_next = (bucket_num + 1) % self.num_buckets
```

Of course this leads to unexpected results !!!

**Comment by alexgarel** [comment]
This seems like the only line affected, but it makes the product bug if `NUM_BUCKETS` is not 2 !

**Comment by sobotklp** [comment]
Oops, that looks like an accidental commit. 

I was actually thinking of removing support for `NUM_BUCKETS` since I can't think of many cases where you'd want to set it > 2. What is your use case?

**Comment by sobotklp** [comment]
I've uploaded a new version 0.5.9 to PyPI that has reverts the change to `throttle/zone/__init.py`.

**Comment by alexgarel** [comment]
My use case, was mainly to be able to diagnose for how long the peak was running.
But it's not a very important use case (I can also look at access log for that).
