### ISSUE TITLE
pip install django-throttle-requests fails

### ISSUE THREAD

**Issue by jumpchat** [sobotklp/django-throttle-requests#3]
doesn't seem to be in the pip list of packages.

**Comment by sobotklp** [comment]
That was because I had never actually published it to PyPi. It it on there now though: https://pypi.python.org/pypi/django-throttle-requests/0.5.0

Thanks for reminding me!

**Comment by jumpchat** [comment]
Hooray!  It works. Thanks.

**Comment by jumpchat** [comment]
It looks like backends, test, and zones directory are not installed properly in 0.5.0.

Downloading/unpacking django-throttle-requests
  Downloading django-throttle-requests-0.5.0.tar.gz
  Running setup.py (path:/private/var/folders/rt/3d7ylsbj7y1f_5fd2s7nl1wr0000gp/T/pip_build_yulius/django-throttle-requests/setup.py) egg_info for package django-throttle-requests
    
    warning: no previously-included files matching '*.py' found under directory 'throttle/tests/'
Requirement already satisfied (use --upgrade to upgrade): Django>=1.3.7 in /usr/local/lib/python2.7/site-packages (from django-throttle-requests)
Installing collected packages: django-throttle-requests
  Running setup.py install for django-throttle-requests
    
    warning: no previously-included files matching '*.py' found under directory 'throttle/tests/'
Successfully installed django-throttle-requests

**Comment by sobotklp** [comment]
My bad again. Just released 0.5.2, which installs the throttle/backends and throttle/zones folders.

**Comment by sobotklp** [comment]
Please let me know if you have further issues.
