### ISSUE TITLE
Memcached can't take key with the spaces.

### ISSUE THREAD

**Issue by bvsn** [sobotklp/django-throttle-requests#4]
When using the default RemoteIp handler you can catch the following exception:
`
ip = "100.200.300.400, 101.201.301.401"
`
With this ip you catch the following exception:
`
MemcachedKeyCharacterError: Control/space characters not allowed (key=':1:key:100.200.300.400, 101.201.301.401:0')
`

**Comment by bvsn** [comment]
As a workaround, you can use hashlib and generate a unique key.

**Comment by sobotklp** [comment]
Good catch! That situation would happen if there is more than one reverse proxy between the client and your Django application. 

Would you like to submit a PR?

**Comment by sobotklp** [comment]
Merged and released version 0.5.3 to PyPI. Thanks @bvsn
